### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ChrisVasterling** [forivall/atom-remember-folds#16]
For some reason it sometimes won't remember the folds in my css file. My HTML and JS files are fine but css will randomly unfold on startup.

**Comment by forivall** [comment]
@ChrisVasterling Do you have an example file? Worked fine for me with https://gist.github.com/forivall/7d5a304a8c3c809f0ba96884a7cf9d7e. Also a list of plugins would be helpful, as there may be something else that is interfering.
