### ISSUE TITLE
Folding not saved

### ISSUE THREAD

**Issue by MiroHibler** [forivall/atom-remember-folds#26]
Foldings are not saved with:

- OSX High Sierra Dev Beta (17A352a)
- Atom v1.19.3
- remember-fold v0.3.0

(there's no console log error)

- Open file from tree menu
- Fold code in file
- Close file
- Open the same file from tree menu

**Comment by forivall** [comment]
Could not reproduce, atom v1.19.7, osx sierra (1.12.7)

@MiroHibler Could you open up dev tools, put `atom.getStateKey(atom.project.getPaths())` into the console, and then open up this key in the indexedDB viewer in the debugger? See screenshot for how to do this:

<img width="1415" alt="screen shot 2017-09-11 at 3 54 44 pm" src="https://user-images.githubusercontent.com/760204/30300490-c2571556-9709-11e7-93c3-09adc102fb5a.png">

And send me a screenshot for the folds state for a file you're trying to use.

**Comment by MiroHibler** [comment]
Sorry, I somehow missed your answer...

Anyways, FYI, I'm now on atom v1.21.1 and osx high sierra (10.13.1 Beta (17B35a)) and the problem persists.

Here's the screenshot:

![screen shot 2017-10-19 at 09 47 11](https://user-images.githubusercontent.com/1636676/31759816-ee8ef08c-b4b2-11e7-9c49-fcec50f09212.png)

**Comment by MiroHibler** [comment]
Okay, I might be on to something... While my computer slowed down to a crowl (for other reasons than Atom ;), I noticed that files have been loaded with folds, but as soon as syntax highliter ([semanticolor](https://atom.io/packages/semanticolor) in this case) kicked in, it unfolds the code and leaves it unfolded.

So, I'm closing this issue because the cause is somewhere else :)
