### ISSUE TITLE
Package is deprecated

### ISSUE THREAD

**Issue by binaryfunt** [forivall/atom-remember-folds#31]
Atom now remembers folds natively (as of v1.35.0 at least).

**Comment by solsticedhiver** [comment]
Really ?
I don't see this happening right now in atom 1.37. Does it need a setting to do so ? a command to be run, a shortcut to be stroked ?

Because I just installed this plugin so that folds are rembered.

**Comment by binaryfunt** [comment]
@solsticedhiver Hmm... Are you using tree sitter parsers (`Settings > Core > Use Tree Sitters Parsers`)? I am and it's remembering folds for me.

**Comment by solsticedhiver** [comment]
@binaryfunt oh in fact it seems to work after all. sorry

Edit:
well, it does not seem to work well when you switch branch and the same file is different on each branch

**Comment by forivall** [comment]
Do either of you know if there's a way to mark a package as deprecated in the atom package registry? I've switched to vscode, so my knowledge on atom packages, and where to even look in the docs isn't up to date.

**Comment by binaryfunt** [comment]
> well, it does not seem to work well when you switch branch and the same file is different on each branch

Yeah, the native remembering is not perfect unfortunately. However, it seems like this package might conflict with the current versions of Atom (#30)

**Comment by binaryfunt** [comment]
@forivall From what I can tell, you might have to submit a pull request asking for it to be marked as deprecated (https://discuss.atom.io/t/how-to-mark-a-package-as-deprecated/34745/3). I don't know if this works but it's also possible to set a maximum version of Atom in the package.json

```json
"engines": {
  "atom": ">=1.0.0 <2.0.0"
}
```

 I guess a simpler/safer option may be to just warn people in the package description line.

**Comment by MikeWillis** [comment]
Has anyone gotten fold-saving to work on native Atom? For me it doesn't seem to be possible, and as has been mentioned, this package no longer works with the latest Atom

**Comment by forivall** [comment]
I've received reports that it does work natively (requiring tree-sitter enabled), and I was working on making a nice tool to mark this as deprecated.

Can anyone who's actively using atom comment? (as i'm not actively using atom)

**Comment by m-vz** [comment]
I just tested this with `1.46.0` and didn't experience any of the open issues.

From my testing (with and without tree-sitter), Atom natively remembers folding for closed windows, but if a single file tab is closed and reopened, it doesn't remember the folds. So this package still has an advantage over how atom handles things.

**Comment by forivall** [comment]
Thanks for the info Milan! Closing this out.
