### ISSUE TITLE
Loading time

### ISSUE THREAD

**Issue by ghost** [forivall/atom-remember-folds#32]
After open as a project "coffee-compile" plugin and modify some files then "folds" plugin cames to take 52seconds or more.

**Comment by kuntur-studio** [comment]
On my PC (Ubuntu i7, 8GB RAM), this plugin makes atom unresponsive when opening just a simple yaml file with 10+ folds.
I ended up uninstalling it.

**Comment by forivall** [comment]
Please take note of the notice in the readme.

When i initially developed this, i was using a laptop from 2007 with a core 2 duo and 4GB ram on arch linux. It should be possible to find the issue, if you're able to look into it.

**Comment by forivall** [comment]
Duplication of #30
