### ISSUE TITLE
Folding not saved after updating to 1.9.5 

### ISSUE THREAD

**Issue by andyrichardson** [forivall/atom-remember-folds#4]
After updating to _Atom 1.9.5_, folds are no longer being saved.

How to replicate:
 * Open file from tree menu
 * Fold function in file
 * Close file
 * Open same file from tree menu

**Comment by andyrichardson** [comment]
Started in dev mode and got the following error.

`TextEditor.prototype.displayBuffer` has always been private, but now
it is gone. Reading the `displayBuffer` property now returns a reference
to the containing `TextEditor`, which now provides *some* of the API of
the defunct `DisplayBuffer` class.
```
TextEditor.module.exports.Object.defineProperty.get (/usr/lib64/atom/src/text-editor.js:87:14)
<unknown> (/home/andy/.atom/packages/remember-folds/lib/remember-folds.js:36:17)
Function.module.exports.Emitter.simpleDispatch (/usr/lib64/atom/node_modules/event-kit/lib/emitter.js:25:14)
Emitter.emit (/usr/lib64/atom/node_modules/event-kit/lib/emitter.js:125:28)
PaneContainer.didDestroyPaneItem (/usr/lib64/atom/src/pane-container.js:302:27)
Pane.removeItem (/usr/lib64/atom/src/pane.js:578:17)
```

**Comment by andyrichardson** [comment]
Fixing the issue in a fork as we speak. I've correctly implemented the fold caching but there seems to be an issue with rendering the _fold marker layer_ after adding a marker.

**Comment by forivall** [comment]
Fixed with #5. Thanks!

**Comment by MiroHibler** [comment]
Having the same issue:

- Open file from tree menu
- Fold function in file
- Close file
- Open same file from tree menu

(minus console log error) with:

- OSX High Sierra Dev Beta (17A352a)
- Atom v1.19.3
- remember-fold v0.3.0

**Comment by andyrichardson** [comment]
@MiroHibler This issue has been solved months ago. You should probably create a new one if you're experiencing complications.
